<?php

namespace Database\Seeders;

use App\Models\ClassRoom;
use Illuminate\Database\Seeder;

class ClassRoomSeeder extends Seeder
{
  public function run(): void
  {
    $class_rooms = [
      [
        'id' => 1,
        'sub_activity_id' => 1,
        'unit_id' => 9,
        'description' => 'Cursos Técnico e/ ou Licencituras com base na lei 11.892 de 29 de dezembro de 2008 (Mínimo de 6 horas)',
        'weight' => 1.00,
        'max' => 20,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 2,
        'sub_activity_id' => 1,
        'unit_id' => 9,
        'description' => 'Cursos de Especialização Técnica, Graduação e Pós-Graduação (lato sensu e stricto sensu)',
        'weight' => 1.00,
        'max' => 20,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 3,
        'sub_activity_id' => 1,
        'unit_id' => 12,
        'description' => 'Cursos FIC (Observar o Art.7, §4º regulamentação da carga horária)',
        'weight' => 0.05,
        'max' => 400,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 4,
        'sub_activity_id' => 2,
        'unit_id' => 15,
        'description' => 'Preparação + Planejamento',
        'weight' => 0.8,
        'max' => 14,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 5,
        'sub_activity_id' => 2,
        'unit_id' => 15,
        'description' => 'Atendimento a Estudantes',
        'weight' => 0.2,
        'max' => 4,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 6,
        'sub_activity_id' => 3,
        'unit_id' => 0,
        'description' => 'Participação nos encontros técnico-pedagógicos, reuniões com os diversos setores da gestão',
        'weight' => 1,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 7,
        'sub_activity_id' => 4,
        'unit_id' => 13,
        'description' => 'Orientação de TCC graduação',
        'weight' => 1,
        'max' => 6,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 8,
        'sub_activity_id' => 4,
        'unit_id' => 13,
        'description' => 'Orientação de Estágio Supervisionado (Supervisor-Orientador)',
        'weight' => 1,
        'max' => 4,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 9,
        'sub_activity_id' => 4,
        'unit_id' => 17,
        'description' => 'Orientação de Estágio Supervisionado (Curso com regulamentação diferenciada em Conselho de Classe Profissional)',
        'weight' => 2,
        'max' => 4,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 10,
        'sub_activity_id' => 4,
        'unit_id' => 13,
        'description' => 'Monitoria',
        'weight' => 2,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 11,
        'sub_activity_id' => 4,
        'unit_id' => 7,
        'description' => 'Programa Institucional de Bolsas de Iniciação à Docência (PIBID) ou outro programa voltado a Permanência e Êxito',
        'weight' => 10,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 12,
        'sub_activity_id' => 5,
        'unit_id' => 16,
        'description' => 'Responsável por Laboratório',
        'weight' => 8,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 13,
        'sub_activity_id' => 5,
        'unit_id' => 22,
        'description' => 'Projetos ou atividades complementares de ensino extracurriculares',
        'weight' => 1,
        'max' => 2,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 14,
        'sub_activity_id' => 6,
        'unit_id' => 22,
        'description' => 'Coordenação de projeto de pesquisa aplicada, desenvolvimento ou inovação cadastrado na PRPI com fomento IFCE ou sem recursos',
        'weight' => 4,
        'max' => 3,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 15,
        'sub_activity_id' => 6,
        'unit_id' => 22,
        'description' => 'Coordenação de projeto de pesquisa aplicada, desenvolvimento ou inovação cadastrado na PRPI com captação de recursos externos ao IFCE',
        'weight' => 6,
        'max' => 2,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 16,
        'sub_activity_id' => 6,
        'unit_id' => 22,
        'description' => 'Participação na equipe de projeto de pesquisa aplicada, desenvolvimento ou inovação, cadastrado na PRPI',
        'weight' => 3,
        'max' => 2,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 17,
        'sub_activity_id' => 6,
        'unit_id' => 13,
        'description' => 'Orientação em especialização e Co-orientação em Mestrado ou Doutorado do IFCE ou em outra instituição de ensino superior com anuência do IFCE',
        'weight' => 2,
        'max' => 4,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 18,
        'sub_activity_id' => 6,
        'unit_id' => 4,
        'description' => 'Bolsista produtividade PQ, DT do CNPq',
        'weight' => 16,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 19,
        'sub_activity_id' => 6,
        'unit_id' => 21,
        'description' => 'Participação em programa de pós-graduação em nível de mestrado ou doutorado como docente COLABORADOR (do IFCE ou outra IES com anuência)',
        'weight' => 8,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 20,
        'sub_activity_id' => 6,
        'unit_id' => 21,
        'description' => 'Participação em programa de pós-graduação em nível de mestrado ou doutorado como docente PERMANENTE (do IFCE ou outra IES com anuência)',
        'weight' => 16,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 21,
        'sub_activity_id' => 7,
        'unit_id' => 22,
        'description' => 'Coordenação de projeto/programa de extensão cadastrado na PROEXT com fomento IFCE ou sem recursos',
        'weight' => 4,
        'max' => 3,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 22,
        'sub_activity_id' => 7,
        'unit_id' => 22,
        'description' => 'Coordenação de projeto/programa de extensão cadastrado na PROEXT com captação de recursos externos ao IFCE',
        'weight' => 6,
        'max' => 2,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 23,
        'sub_activity_id' => 7,
        'unit_id' => 22,
        'description' => 'Participação na equipe de projeto ou programa de extensão, cadastrado na PROEXT, exceto aula FIC',
        'weight' => 3,
        'max' => 2,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 24,
        'sub_activity_id' => 7,
        'unit_id' => 8,
        'description' => 'Coordenação de incubadoras de empresas',
        'weight' => 16,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 25,
        'sub_activity_id' => 7,
        'unit_id' => 8,
        'description' => 'Coordenação dos NAPNEs e NEABIs',
        'weight' => 5,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 26,
        'sub_activity_id' => 7,
        'unit_id' => 18,
        'description' => 'Paticipação em NAPNEs e NEABIs',
        'weight' => 3,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 27,
        'sub_activity_id' => 7,
        'unit_id' => 12,
        'description' => 'Cursos FIC (Quantidade de horas por curso)',
        'weight' => 0.05,
        'max' => 240,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 28,
        'sub_activity_id' => 7,
        'unit_id' => 15,
        'description' => 'Preparação + Planejamento dos cursos FIC',
        'weight' => 0.05,
        'max' => 120,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 29,
        'sub_activity_id' => 7,
        'unit_id' => 14,
        'description' => 'Planejamento e organização de eventos de extensão',
        'weight' => 1,
        'max' => 2,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 30,
        'sub_activity_id' => 8,
        'unit_id' => 10,
        'description' => 'Coordenador de Curso',
        'weight' => 18,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 31,
        'sub_activity_id' => 8,
        'unit_id' => 23,
        'description' => 'Coordenador de Setor',
        'weight' => 18,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 32,
        'sub_activity_id' => 8,
        'unit_id' => 11,
        'description' => 'Chefe de Departamento',
        'weight' => 18,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 33,
        'sub_activity_id' => 8,
        'unit_id' => 1,
        'description' => 'Diretores de Área/Setor',
        'weight' => 18,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 34,
        'sub_activity_id' => 8,
        'unit_id' => 3,
        'description' => 'Assessor da Reitoria',
        'weight' => 18,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 35,
        'sub_activity_id' => 8,
        'unit_id' => 6,
        'description' => 'Coordenador de Implantação de Campus',
        'weight' => 18,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 36,
        'sub_activity_id' => 8,
        'unit_id' => 2,
        'description' => 'Assistente de Pró-Reitoria ou Chefe de Gabinete de Campus',
        'weight' => 18,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 37,
        'sub_activity_id' => 8,
        'unit_id' => 20,
        'description' => 'Coordenador de programa institucional: ensino, pesquisa ou extensão',
        'weight' => 18,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 38,
        'sub_activity_id' => 9,
        'unit_id' => 0,
        'description' => 'Conselhos, comissões ou comitês permanentes institucionais',
        'weight' => 3,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 39,
        'sub_activity_id' => 9,
        'unit_id' => 0,
        'description' => 'Comissão Própria de Avaliação e Comissão Permanente de Pessoal Docente (Central)',
        'weight' => 8,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 40,
        'sub_activity_id' => 9,
        'unit_id' => 0,
        'description' => 'Comissão Própria de Avaliação e Comissão Permanente de Pessoal Docente (Local)',
        'weight' => 4,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 41,
        'sub_activity_id' => 9,
        'unit_id' => 0,
        'description' => 'Conselhos ou comitês permanentes externos',
        'weight' => 1,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 42,
        'sub_activity_id' => 9,
        'unit_id' => 10,
        'description' => 'Colegiado de Cursos',
        'weight' => 1,
        'max' => 2,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 43,
        'sub_activity_id' => 9,
        'unit_id' => 10,
        'description' => 'Núcleo Docente Estruturante (NDE)',
        'weight' => 1,
        'max' => 2,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 44,
        'sub_activity_id' => 9,
        'unit_id' => 19,
        'description' => 'Comissão de Processo Administrativo Disciplinar',
        'weight' => 4,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 45,
        'sub_activity_id' => 9,
        'unit_id' => 0,
        'description' => 'Participação em Direção Sindical como titular',
        'weight' => 4,
        'max' => 1,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
      [
        'id' => 46,
        'sub_activity_id' => 9,
        'unit_id' => 5,
        'description' => 'Fiscalização de contrato',
        'weight' => 1,
        'max' => 2,
        'class' => null,
        'class_time' => null,
        'day_month_year' => null,
        'created_at' => '2024-11-08 00:00:00.000',
        'updated_at' => null,
      ],
    ];

    foreach ($class_rooms as $class_room) {
      ClassRoom::create($class_room);
    }
  }
}
